services:
  swag:
      image: lscr.io/linuxserver/swag:latest
      container_name: swag
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Australia/Adelaide
        - URL=hippity.internal
        - VALIDATION=none
        - CERTPROVIDER=selfsigned
      volumes:
        - ./proxy/data:/config
      ports:
        - 443:443
        - 80:80
      restart: unless-stopped
      networks:
      - internal
  
  dns:
    build: 
      context: .
      dockerfile: ./DNS/DockerfileDNS
    container_name: dns_test
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /home/master/temp/DNS:/data
    networks:
      dns_net:
        ipv4_address: 192.168.1.201



  kolibri:
    build:
      context: ./kolibri
      dockerfile: Dockerfilekolibri
    container_name: kolibri_test
    restart: unless-stopped
    volumes:
      - kolibri_data:/kolibri/.kolibri
    networks:
      - internal

  kiwix:
    build:
      context: ./kiwix
      dockerfile: Dockerfilekiwix
    container_name: kiwix_test
    restart: unless-stopped
    volumes:
      - /home/master/temp/kiwix/zim:/data
    command:
      - '*.zim'
    networks:
      - internal
  moodle_db:
    image: docker.io/bitnami/mariadb:latest
    container_name: moodle_db_test
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
    restart: unless-stopped
    volumes:
      - mariadb_data:/bitnami/mariadb
      - ./moodle/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
    networks:
      - internal

  moodle:
    image: docker.io/bitnami/moodle:latest
    container_name: moodle_test
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_HOST=moodle_db
      - BITNAMI_DEBUG=true   
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Admin123!
      - MOODLE_REVERSEPROXY=yes
      - MOODLE_SSLPROXY=yes
      - MOODLE_HOST=moodle.hippity.internal:443
    depends_on:
      - moodle_db
    networks:
      - internal


    # entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata



volumes:
  moodle_data:       # Moodle data
  moodledata_data:
  mariadb_data:

  moodle_db_data:    # Database storage
  kolibri_data:


networks:
  dns_net:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.200/29

  internal:
    driver: bridge